# Tensorflow


In [2]:
import tensorflow as tf

tensor1 = tf.constant([3,4,5])
tensor2 = tf.constant([6,7,8])

tensor1+tensor2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 11, 13])>

In [ ]:
tf.add()
tf.subtract()
tf.divide()
tf.multiply()
tf.matmul()

In [5]:
tf.zeros([2,2,2,3])

<tf.Tensor: shape=(2, 2, 2, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [7]:
# waight 저장하기 위해 variable 만들기
w = tf.Variable(1.0)
w.numpy()       # 값 불러오기
w.assign(2.0)   # 변수 변경


1.0

활성함수 : layer를 가공

활성함수를 통해 비선형적 예측을 가능하게함

loss function : 오차 계산
optimizer : learning rate를 계산





In [12]:
height  = 170
foot = 260

a=tf.Variable(0.1)
b=tf.Variable(0.2)

def lossFunc():
    yhat = height * a+b
    return tf.square((260 - yhat))

opt = tf.keras.optimizers.Adam(learning_rate=0.1)

for i in range(300):
    opt.minimize(lossFunc, var_list=[a,b])
    
a.numpy(), b.numpy() 

(1.5198832, 1.6198834)

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64, activation = 'relu'),
    tf.keras.layers.Dense(128, activation = 'softmax'),
    tf.keras.layers.Dense(32, activation = 'tanh'),
    tf.keras.layers.Dense(1, activation = 'sigmoid') # 0~1 사이의 결과를 알려줌
])

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
#binary_crossentropy : 0과 1 분류, 확률

model.fit(epochs = 10)